#!/bin/bash
#
# Usage: pdftopdfa1 <input file> <output file>
#
# To make this work, you have to
# - update the hardcoded path of the icc file in PDFA_def.ps
# - make sure you have a proper ghostscript version, I've run ith with version 9.52
# - have some luck...
#
DIR=$(dirname "$(readlink -f "$BASH_SOURCE")")
JAR=$(cygpath -w "$DIR/preflight-app-2.0.21.jar")
echo -e "\npdftopdfa1 auxiliary files to be found in $DIR\n" 
echo -e "\nIn case of problems, check the hardcoded path to the icc file in PDFA_def.ps!\n"
echo gs-952 -dPDFA=1 -dNOSAFER -dNOOUTERSAVE -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=3 -o "$2" $DIR/PDFA_def.ps "$1"
gs -dPDFA=1 -dNOSAFER -dNOOUTERSAVE -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=3 -o "$2" $DIR/PDFA_def.ps "$1"
echo java -jar $JAR "$2"
java -jar $JAR "$2"
