#!/bin/bash
#
# Usage: pdftopdfx <input file> <output file>
#
# To make this work, you have to
# - make sure you have a proper ghostscript version (I've run it with version 9.52)
# - have some luck...
#
DIR=$(dirname "$(readlink -f "$BASH_SOURCE")")
echo -e "\npdftopdfx auxiliary files to be found in $DIR\n" 
#echo -e "\nIn case of problems, check the hardcoded path to the icc file in PDFA_def.ps!\n"
echo gs -dPDFX -dNOSAFER -dNOOUTERSAVE -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=3 -o "$2" $DIR/PDFX_def.ps "$1"
gs -dPDFX -dNOSAFER -dNOOUTERSAVE -sColorConversionStrategy=CMYK -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=3 -o "$2" $DIR/PDFX_def.ps "$1"
